package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetMovementRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetMovementRequestAllPropertiesEquals(AssetMovementRequest expected, AssetMovementRequest actual) {
        assertAssetMovementRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetMovementRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetMovementRequestAllUpdatablePropertiesEquals(AssetMovementRequest expected, AssetMovementRequest actual) {
        assertAssetMovementRequestUpdatableFieldsEquals(expected, actual);
        assertAssetMovementRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetMovementRequestAutoGeneratedPropertiesEquals(AssetMovementRequest expected, AssetMovementRequest actual) {
        assertThat(actual)
            .as("Verify AssetMovementRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetMovementRequestUpdatableFieldsEquals(AssetMovementRequest expected, AssetMovementRequest actual) {
        assertThat(actual)
            .as("Verify AssetMovementRequest relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getFromLocationLabel()).as("check fromLocationLabel").isEqualTo(expected.getFromLocationLabel()))
            .satisfies(a -> assertThat(a.getToLocationLabel()).as("check toLocationLabel").isEqualTo(expected.getToLocationLabel()))
            .satisfies(a -> assertThat(a.getEsignWorkflowId()).as("check esignWorkflowId").isEqualTo(expected.getEsignWorkflowId()))
            .satisfies(a -> assertThat(a.getEsignStatus()).as("check esignStatus").isEqualTo(expected.getEsignStatus()))
            .satisfies(a -> assertThat(a.getEsignLastUpdate()).as("check esignLastUpdate").isEqualTo(expected.getEsignLastUpdate()))
            .satisfies(a -> assertThat(a.getSignedAt()).as("check signedAt").isEqualTo(expected.getSignedAt()))
            .satisfies(a -> assertThat(a.getExecutedAt()).as("check executedAt").isEqualTo(expected.getExecutedAt()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetMovementRequestUpdatableRelationshipsEquals(AssetMovementRequest expected, AssetMovementRequest actual) {
        assertThat(actual)
            .as("Verify AssetMovementRequest relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
