package com.ailab.smartasset.domain;

import static com.ailab.smartasset.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AssetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetAllPropertiesEquals(Asset expected, Asset actual) {
        assertAssetAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetAllUpdatablePropertiesEquals(Asset expected, Asset actual) {
        assertAssetUpdatableFieldsEquals(expected, actual);
        assertAssetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetAutoGeneratedPropertiesEquals(Asset expected, Asset actual) {
        assertThat(actual)
            .as("Verify Asset auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetUpdatableFieldsEquals(Asset expected, Asset actual) {
        assertThat(actual)
            .as("Verify Asset relevant properties")
            .satisfies(a -> assertThat(a.getAssetType()).as("check assetType").isEqualTo(expected.getAssetType()))
            .satisfies(a -> assertThat(a.getAssetCode()).as("check assetCode").isEqualTo(expected.getAssetCode()))
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCriticality()).as("check criticality").isEqualTo(expected.getCriticality()))
            .satisfies(a -> assertThat(a.getResponsibleName()).as("check responsibleName").isEqualTo(expected.getResponsibleName()))
            .satisfies(a -> assertThat(a.getCostCenter()).as("check costCenter").isEqualTo(expected.getCostCenter()))
            .satisfies(a -> assertThat(a.getBrand()).as("check brand").isEqualTo(expected.getBrand()))
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()))
            .satisfies(a -> assertThat(a.getSerialNumber()).as("check serialNumber").isEqualTo(expected.getSerialNumber()))
            .satisfies(a ->
                assertThat(a.getPowerKw()).as("check powerKw").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPowerKw())
            )
            .satisfies(a ->
                assertThat(a.getVoltageV()).as("check voltageV").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getVoltageV())
            )
            .satisfies(a ->
                assertThat(a.getCurrentA()).as("check currentA").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCurrentA())
            )
            .satisfies(a ->
                assertThat(a.getCosPhi()).as("check cosPhi").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCosPhi())
            )
            .satisfies(a -> assertThat(a.getSpeedRpm()).as("check speedRpm").isEqualTo(expected.getSpeedRpm()))
            .satisfies(a -> assertThat(a.getIpRating()).as("check ipRating").isEqualTo(expected.getIpRating()))
            .satisfies(a -> assertThat(a.getInsulationClass()).as("check insulationClass").isEqualTo(expected.getInsulationClass()))
            .satisfies(a -> assertThat(a.getMountingType()).as("check mountingType").isEqualTo(expected.getMountingType()))
            .satisfies(a ->
                assertThat(a.getShaftDiameterMm())
                    .as("check shaftDiameterMm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getShaftDiameterMm())
            )
            .satisfies(a ->
                assertThat(a.getFootDistanceAmm())
                    .as("check footDistanceAmm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFootDistanceAmm())
            )
            .satisfies(a ->
                assertThat(a.getFootDistanceBmm())
                    .as("check footDistanceBmm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFootDistanceBmm())
            )
            .satisfies(a ->
                assertThat(a.getFrontFlangeMm())
                    .as("check frontFlangeMm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFrontFlangeMm())
            )
            .satisfies(a ->
                assertThat(a.getRearFlangeMm())
                    .as("check rearFlangeMm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRearFlangeMm())
            )
            .satisfies(a ->
                assertThat(a.getIecAxisHeightMm())
                    .as("check iecAxisHeightMm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getIecAxisHeightMm())
            )
            .satisfies(a -> assertThat(a.getDimensionsSource()).as("check dimensionsSource").isEqualTo(expected.getDimensionsSource()))
            .satisfies(a -> assertThat(a.getHasHeating()).as("check hasHeating").isEqualTo(expected.getHasHeating()))
            .satisfies(a ->
                assertThat(a.getTemperatureProbeType()).as("check temperatureProbeType").isEqualTo(expected.getTemperatureProbeType())
            )
            .satisfies(a ->
                assertThat(a.getLastCommissioningDate()).as("check lastCommissioningDate").isEqualTo(expected.getLastCommissioningDate())
            )
            .satisfies(a ->
                assertThat(a.getLastMaintenanceDate()).as("check lastMaintenanceDate").isEqualTo(expected.getLastMaintenanceDate())
            )
            .satisfies(a -> assertThat(a.getMaintenanceCount()).as("check maintenanceCount").isEqualTo(expected.getMaintenanceCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetUpdatableRelationshipsEquals(Asset expected, Asset actual) {
        assertThat(actual)
            .as("Verify Asset relationships")
            .satisfies(a -> assertThat(a.getSite()).as("check site").isEqualTo(expected.getSite()))
            .satisfies(a -> assertThat(a.getProductionLine()).as("check productionLine").isEqualTo(expected.getProductionLine()))
            .satisfies(a -> assertThat(a.getCurrentZone()).as("check currentZone").isEqualTo(expected.getCurrentZone()));
    }
}
