package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentLinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentLinkAllPropertiesEquals(DocumentLink expected, DocumentLink actual) {
        assertDocumentLinkAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentLinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentLinkAllUpdatablePropertiesEquals(DocumentLink expected, DocumentLink actual) {
        assertDocumentLinkUpdatableFieldsEquals(expected, actual);
        assertDocumentLinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentLinkAutoGeneratedPropertiesEquals(DocumentLink expected, DocumentLink actual) {
        assertThat(actual)
            .as("Verify DocumentLink auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentLinkUpdatableFieldsEquals(DocumentLink expected, DocumentLink actual) {
        assertThat(actual)
            .as("Verify DocumentLink relevant properties")
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getLinkedAt()).as("check linkedAt").isEqualTo(expected.getLinkedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentLinkUpdatableRelationshipsEquals(DocumentLink expected, DocumentLink actual) {
        assertThat(actual)
            .as("Verify DocumentLink relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
