package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GatewayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayAllPropertiesEquals(Gateway expected, Gateway actual) {
        assertGatewayAutoGeneratedPropertiesEquals(expected, actual);
        assertGatewayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayAllUpdatablePropertiesEquals(Gateway expected, Gateway actual) {
        assertGatewayUpdatableFieldsEquals(expected, actual);
        assertGatewayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayAutoGeneratedPropertiesEquals(Gateway expected, Gateway actual) {
        assertThat(actual)
            .as("Verify Gateway auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayUpdatableFieldsEquals(Gateway expected, Gateway actual) {
        assertThat(actual)
            .as("Verify Gateway relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVendor()).as("check vendor").isEqualTo(expected.getVendor()))
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()))
            .satisfies(a -> assertThat(a.getMacAddress()).as("check macAddress").isEqualTo(expected.getMacAddress()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getInstalledAt()).as("check installedAt").isEqualTo(expected.getInstalledAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayUpdatableRelationshipsEquals(Gateway expected, Gateway actual) {
        assertThat(actual)
            .as("Verify Gateway relationships")
            .satisfies(a -> assertThat(a.getSite()).as("check site").isEqualTo(expected.getSite()))
            .satisfies(a -> assertThat(a.getZone()).as("check zone").isEqualTo(expected.getZone()));
    }
}
