package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocationEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationEventAllPropertiesEquals(LocationEvent expected, LocationEvent actual) {
        assertLocationEventAutoGeneratedPropertiesEquals(expected, actual);
        assertLocationEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationEventAllUpdatablePropertiesEquals(LocationEvent expected, LocationEvent actual) {
        assertLocationEventUpdatableFieldsEquals(expected, actual);
        assertLocationEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationEventAutoGeneratedPropertiesEquals(LocationEvent expected, LocationEvent actual) {
        assertThat(actual)
            .as("Verify LocationEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationEventUpdatableFieldsEquals(LocationEvent expected, LocationEvent actual) {
        assertThat(actual)
            .as("Verify LocationEvent relevant properties")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getObservedAt()).as("check observedAt").isEqualTo(expected.getObservedAt()))
            .satisfies(a -> assertThat(a.getZoneConfidence()).as("check zoneConfidence").isEqualTo(expected.getZoneConfidence()))
            .satisfies(a -> assertThat(a.getRssi()).as("check rssi").isEqualTo(expected.getRssi()))
            .satisfies(a -> assertThat(a.getTxPower()).as("check txPower").isEqualTo(expected.getTxPower()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getAccuracyMeters()).as("check accuracyMeters").isEqualTo(expected.getAccuracyMeters()))
            .satisfies(a -> assertThat(a.getSpeedKmh()).as("check speedKmh").isEqualTo(expected.getSpeedKmh()))
            .satisfies(a -> assertThat(a.getGnssConstellation()).as("check gnssConstellation").isEqualTo(expected.getGnssConstellation()))
            .satisfies(a -> assertThat(a.getRawPayload()).as("check rawPayload").isEqualTo(expected.getRawPayload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationEventUpdatableRelationshipsEquals(LocationEvent expected, LocationEvent actual) {
        assertThat(actual)
            .as("Verify LocationEvent relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()))
            .satisfies(a -> assertThat(a.getSensor()).as("check sensor").isEqualTo(expected.getSensor()))
            .satisfies(a -> assertThat(a.getMatchedSite()).as("check matchedSite").isEqualTo(expected.getMatchedSite()))
            .satisfies(a -> assertThat(a.getMatchedZone()).as("check matchedZone").isEqualTo(expected.getMatchedZone()));
    }
}
