package com.ailab.smartasset.domain;

import static com.ailab.smartasset.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MaintenanceEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceEventAllPropertiesEquals(MaintenanceEvent expected, MaintenanceEvent actual) {
        assertMaintenanceEventAutoGeneratedPropertiesEquals(expected, actual);
        assertMaintenanceEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceEventAllUpdatablePropertiesEquals(MaintenanceEvent expected, MaintenanceEvent actual) {
        assertMaintenanceEventUpdatableFieldsEquals(expected, actual);
        assertMaintenanceEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceEventAutoGeneratedPropertiesEquals(MaintenanceEvent expected, MaintenanceEvent actual) {
        assertThat(actual)
            .as("Verify MaintenanceEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceEventUpdatableFieldsEquals(MaintenanceEvent expected, MaintenanceEvent actual) {
        assertThat(actual)
            .as("Verify MaintenanceEvent relevant properties")
            .satisfies(a -> assertThat(a.getMaintenanceType()).as("check maintenanceType").isEqualTo(expected.getMaintenanceType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getPlannedAt()).as("check plannedAt").isEqualTo(expected.getPlannedAt()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTechnician()).as("check technician").isEqualTo(expected.getTechnician()))
            .satisfies(a -> assertThat(a.getDowntimeMinutes()).as("check downtimeMinutes").isEqualTo(expected.getDowntimeMinutes()))
            .satisfies(a ->
                assertThat(a.getCostAmount())
                    .as("check costAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostAmount())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceEventUpdatableRelationshipsEquals(MaintenanceEvent expected, MaintenanceEvent actual) {
        assertThat(actual)
            .as("Verify MaintenanceEvent relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
