package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductionLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionLineAllPropertiesEquals(ProductionLine expected, ProductionLine actual) {
        assertProductionLineAutoGeneratedPropertiesEquals(expected, actual);
        assertProductionLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionLineAllUpdatablePropertiesEquals(ProductionLine expected, ProductionLine actual) {
        assertProductionLineUpdatableFieldsEquals(expected, actual);
        assertProductionLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionLineAutoGeneratedPropertiesEquals(ProductionLine expected, ProductionLine actual) {
        assertThat(actual)
            .as("Verify ProductionLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionLineUpdatableFieldsEquals(ProductionLine expected, ProductionLine actual) {
        assertThat(actual)
            .as("Verify ProductionLine relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductionLineUpdatableRelationshipsEquals(ProductionLine expected, ProductionLine actual) {
        assertThat(actual)
            .as("Verify ProductionLine relationships")
            .satisfies(a -> assertThat(a.getSite()).as("check site").isEqualTo(expected.getSite()));
    }
}
