package com.ailab.smartasset.domain;

import static com.ailab.smartasset.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SensorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorAllPropertiesEquals(Sensor expected, Sensor actual) {
        assertSensorAutoGeneratedPropertiesEquals(expected, actual);
        assertSensorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorAllUpdatablePropertiesEquals(Sensor expected, Sensor actual) {
        assertSensorUpdatableFieldsEquals(expected, actual);
        assertSensorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorAutoGeneratedPropertiesEquals(Sensor expected, Sensor actual) {
        assertThat(actual)
            .as("Verify Sensor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorUpdatableFieldsEquals(Sensor expected, Sensor actual) {
        assertThat(actual)
            .as("Verify Sensor relevant properties")
            .satisfies(a -> assertThat(a.getSensorType()).as("check sensorType").isEqualTo(expected.getSensorType()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a ->
                assertThat(a.getMinThreshold())
                    .as("check minThreshold")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinThreshold())
            )
            .satisfies(a ->
                assertThat(a.getMaxThreshold())
                    .as("check maxThreshold")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaxThreshold())
            )
            .satisfies(a -> assertThat(a.getInstalledAt()).as("check installedAt").isEqualTo(expected.getInstalledAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorUpdatableRelationshipsEquals(Sensor expected, Sensor actual) {
        assertThat(actual)
            .as("Verify Sensor relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
