package com.ailab.smartasset.domain;

import static com.ailab.smartasset.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SensorMeasurementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSensorMeasurementAllPropertiesEquals(SensorMeasurement expected, SensorMeasurement actual) {
        assertSensorMeasurementAutoGeneratedPropertiesEquals(expected, actual);
        assertSensorMeasurementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships)
     * set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSensorMeasurementAllUpdatablePropertiesEquals(SensorMeasurement expected, SensorMeasurement actual) {
        assertSensorMeasurementUpdatableFieldsEquals(expected, actual);
        assertSensorMeasurementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties
     * (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSensorMeasurementAutoGeneratedPropertiesEquals(SensorMeasurement expected, SensorMeasurement actual) {
        assertThat(actual)
            .as("Verify SensorMeasurement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSensorMeasurementUpdatableFieldsEquals(SensorMeasurement expected, SensorMeasurement actual) {
        assertThat(actual)
            .as("Verify SensorMeasurement relevant properties")
            .satisfies(a -> assertThat(a.getMeasuredAt()).as("check measuredAt").isEqualTo(expected.getMeasuredAt()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getQuality()).as("check quality").isEqualTo(expected.getQuality()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSensorMeasurementUpdatableRelationshipsEquals(SensorMeasurement expected, SensorMeasurement actual) {
        assertThat(actual)
            .as("Verify SensorMeasurement relationships")
            .satisfies(a -> assertThat(a.getSensor()).as("check sensor").isEqualTo(expected.getSensor()));
    }
}
