package com.ailab.smartasset.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSystemEventAllPropertiesEquals(SystemEvent expected, SystemEvent actual) {
        assertSystemEventAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships)
     * set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSystemEventAllUpdatablePropertiesEquals(SystemEvent expected, SystemEvent actual) {
        assertSystemEventUpdatableFieldsEquals(expected, actual);
        assertSystemEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties
     * (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSystemEventAutoGeneratedPropertiesEquals(SystemEvent expected, SystemEvent actual) {
        assertThat(actual)
            .as("Verify SystemEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSystemEventUpdatableFieldsEquals(SystemEvent expected, SystemEvent actual) {
        assertThat(actual)
            .as("Verify SystemEvent relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCorrelationId()).as("check correlationId").isEqualTo(expected.getCorrelationId()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual   the actual entity
     */
    public static void assertSystemEventUpdatableRelationshipsEquals(SystemEvent expected, SystemEvent actual) {
        assertThat(actual)
            .as("Verify SystemEvent relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
